import { useEffect, useCallback, useState } from 'react';
import { useAppDispatch, useAppSelector } from '@/store/hooks';
import { setSummary, setRecentActivity, setOrderTrends, setRevenueTrends, setUserTrends, setDashboardLoading } from '@/store/slices/dashboardSlice';
import type { ChartDataPoint, DashboardSummary } from '@/store/slices/dashboardSlice';
import axiosInstance from '@/api/axiosInstance';
import SummaryCard from '@/components/admin/dashboard/SummaryCard';
import TrendChart from '@/components/admin/dashboard/TrendChart';
import ActivityFeed from '@/components/admin/dashboard/ActivityFeed';
import LowStockAlerts from '@/components/admin/dashboard/LowStockAlerts';

interface LowStockProduct { id: number; name: string; sku: string; stockQuantity: number; thumbnailUrl?: string | null; }
const demoSummary: DashboardSummary = { totalOrders: 48, totalProducts: 13, totalUsers: 22, totalEmployees: 4, pendingApprovals: 3, lowStockCount: 2, revenue: 128450, totalEnquiries: 17 };
const demoOrders: ChartDataPoint[] = [{ label: 'Mon', value: 4 }, { label: 'Tue', value: 7 }, { label: 'Wed', value: 5 }, { label: 'Thu', value: 9 }, { label: 'Fri', value: 12 }, { label: 'Sat', value: 8 }, { label: 'Sun', value: 11 }];
const demoRevenue: ChartDataPoint[] = [{ label: 'Mon', value: 8200 }, { label: 'Tue', value: 15400 }, { label: 'Wed', value: 11900 }, { label: 'Thu', value: 21600 }, { label: 'Fri', value: 28900 }, { label: 'Sat', value: 18750 }, { label: 'Sun', value: 23700 }];
const demoUsers: ChartDataPoint[] = [{ label: 'Mon', value: 2 }, { label: 'Tue', value: 4 }, { label: 'Wed', value: 3 }, { label: 'Thu', value: 5 }, { label: 'Fri', value: 6 }, { label: 'Sat', value: 4 }, { label: 'Sun', value: 5 }];
const demoActivity = [{ id: -1, userId: null, actionType: 'ORDER_PLACED', entityType: 'demo', entityId: null, details: '[DEMO] GC-DEMO-1048 placed for Rs. 4,899', ipAddress: null, timestamp: new Date(Date.now() - 12 * 60000).toISOString() }, { id: -2, userId: null, actionType: 'ORDER_UPDATED', entityType: 'demo', entityId: null, details: '[DEMO] GC-DEMO-1047 marked as dispatched', ipAddress: null, timestamp: new Date(Date.now() - 48 * 60000).toISOString() }];

export default function DashboardPage() {
  const dispatch = useAppDispatch();
  const { summary, recentActivity, orderTrends, revenueTrends, userTrends, loading } = useAppSelector((state) => state.dashboard);
  const [lowStockProducts, setLowStockProducts] = useState<LowStockProduct[]>([]);
  const [lowStockLoading, setLowStockLoading] = useState(false);
  const fetchSummary = useCallback(async () => { try { const res = await axiosInstance.get('/dashboard/summary'); const d = res.data.data; dispatch(setSummary({ totalOrders: d.totalOrders, totalProducts: d.totalProducts, totalUsers: d.totalUsers, totalEmployees: d.totalEmployees, pendingApprovals: d.pendingApprovals, lowStockCount: d.lowStockCount, revenue: d.totalRevenue ?? d.revenue ?? 0, totalEnquiries: d.totalEnquiries })); } catch {} }, [dispatch]);
  const fetchActivity = useCallback(async () => { try { const res = await axiosInstance.get('/dashboard/activity', { params: { limit: 20 } }); dispatch(setRecentActivity(res.data.data)); } catch {} }, [dispatch]);
  const fetchChart = useCallback(async (endpoint: string, setter: (data: ChartDataPoint[]) => void, period = '30d') => { try { const res = await axiosInstance.get(endpoint, { params: { period } }); const chart = res.data.data; setter(chart.labels?.map((label: string, index: number) => ({ label, value: chart.datasets?.[0]?.data?.[index] ?? 0 })) ?? []); } catch {} }, []);
  const fetchLowStock = useCallback(async () => { setLowStockLoading(true); try { const res = await axiosInstance.get('/dashboard/low-stock', { params: { threshold: 10 } }); setLowStockProducts(res.data.data ?? []); } catch {} finally { setLowStockLoading(false); } }, []);
  useEffect(() => { dispatch(setDashboardLoading(true)); Promise.all([fetchSummary(), fetchActivity(), fetchChart('/dashboard/charts/orders', (data) => dispatch(setOrderTrends(data))), fetchChart('/dashboard/charts/revenue', (data) => dispatch(setRevenueTrends(data))), fetchChart('/dashboard/charts/users', (data) => dispatch(setUserTrends(data))), fetchLowStock()]).finally(() => dispatch(setDashboardLoading(false))); }, [dispatch, fetchSummary, fetchActivity, fetchChart, fetchLowStock]);
  const isDemo = !loading && (!summary || summary.totalOrders === 0);
  const s = isDemo ? demoSummary : summary;
  const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
  const cards = [['Total Orders', s?.totalOrders ?? '-', '🛒', '#a06b3a'], ['Total Products', s?.totalProducts ?? '-', '📦', '#8a6d5a'], ['Total Users', s?.totalUsers ?? '-', '👥', '#6b5544'], ['Revenue', s ? money(s.revenue) : '-', '💰', '#7a4f28']] as const;
  return <div className="min-h-full space-y-6 bg-[#f4ede1] p-6">
    <section className="rounded-2xl bg-gradient-to-r from-[#7a4f28] via-[#a06b3a] to-[#8a6d5a] px-6 py-5 text-white shadow-[0_18px_42px_rgba(122,79,40,0.18)]"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#f4ede1]">Glyde experience centre</p><h1 className="mt-1 font-display text-3xl font-semibold">Store dashboard</h1><p className="mt-1 text-sm text-[#f4ede1]/80">Orders, customer interest and stock movement at a glance.</p></div>{isDemo && <span className="w-fit rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-semibold text-[#faf5ea]">DEMO DATA · NOT REAL SALES</span>}</div></section>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([title, value, icon, color]) => <SummaryCard key={title} title={title} value={value} icon={<span>{icon}</span>} color={color} />)}</div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><TrendChart title="Order Trends" labels={(orderTrends.length ? orderTrends : demoOrders).map(p => p.label)} data={(orderTrends.length ? orderTrends : demoOrders).map(p => p.value)} color="#a06b3a" chartType="bar" loading={loading} onPeriodChange={(period) => fetchChart('/dashboard/charts/orders', (data) => dispatch(setOrderTrends(data)), period)} /><TrendChart title="Revenue Trends" labels={(revenueTrends.length ? revenueTrends : demoRevenue).map(p => p.label)} data={(revenueTrends.length ? revenueTrends : demoRevenue).map(p => p.value)} color="#7a4f28" chartType="line" loading={loading} onPeriodChange={(period) => fetchChart('/dashboard/charts/revenue', (data) => dispatch(setRevenueTrends(data)), period)} /><TrendChart title="Customer Trends" labels={(userTrends.length ? userTrends : demoUsers).map(p => p.label)} data={(userTrends.length ? userTrends : demoUsers).map(p => p.value)} color="#8a6d5a" chartType="bar" loading={loading} onPeriodChange={(period) => fetchChart('/dashboard/charts/users', (data) => dispatch(setUserTrends(data)), period)} /></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><div className="lg:col-span-2 rounded-xl border border-[#2c2c2c]/12 bg-[#faf5ea] p-5 shadow-sm"><h3 className="mb-4 text-sm font-semibold text-[#2c2c2c]">Recent Activity</h3><ActivityFeed activities={(recentActivity.length ? recentActivity : demoActivity) as any[]} loading={loading} /></div><div className="rounded-xl border border-[#2c2c2c]/12 bg-[#faf5ea] p-5 shadow-sm"><h3 className="mb-4 text-sm font-semibold text-[#2c2c2c]">Low Stock Alerts</h3><LowStockAlerts products={lowStockProducts} loading={lowStockLoading} /></div></div>
  </div>;
}
